version: 2

models:
  - name: stg_stock_prices
    description: "Cleaned stock price data"
    columns:
      - name: ticker
        tests:
          - not_null
      - name: date
        tests:
          - not_null
      - name: close_price
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true
      - name: volume
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true

    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - ticker
            - date